### ISSUE TITLE
[PE-D] Formatting issue with documentation

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-TIC4002-F18-1/tp2#49]
The bye and quit should be formatted similarly to exit

![image.png](https://raw.githubusercontent.com/IcyNoPeople/ped/main/files/c3e5431f-ba77-438e-9aa6-48f7bb39bd5c.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: IcyNoPeople/ped#4

**Comment by spencernah** [comment]
Fixed with PR "New Commands and some PE-D fixes"
