### ISSUE TITLE
[PE-D] Help command does not provide the correct link to the correct user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-TIC4002-F18-1/tp2#55]
User inputs or clicks on help

Actual Output: Link is https://se-education.org/addressbook-level3/UserGuide.html
Expected Output: Link should be https://ay2122s2-tic4002-f18-1.github.io/tp2/UserGuide.html

Refer to attached:

![image.png](https://raw.githubusercontent.com/zcnmashleu95/ped/main/files/5c4892f5-2dae-4319-a9a6-78935cfbd224.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: zcnmashleu95/ped#3

**Comment by IcyNoPeople** [comment]
same as issue 43
https://github.com/AY2122S2-TIC4002-F18-1/tp2/issues/43
